In [19]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [20]:
path = "https://raw.githubusercontent.com/amankharwal/Website-data/master/BRCA.csv"

In [21]:
data = pd.read_csv(path)
data.head()

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
2,TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive
3,TCGA-D8-A1XR,56.0,FEMALE,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56.0,FEMALE,0.221550,1.90680,0.52045,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead

In [22]:
# check for null values
print(data.isnull().sum())

Patient_ID             7
Age                    7
Gender                 7
Protein1               7
Protein2               7
Protein3               7
Protein4               7
Tumour_Stage           7
Histology              7
ER status              7
PR status              7
HER2 status            7
Surgery_type           7
Date_of_Surgery        7
Date_of_Last_Visit    24
Patient_Status        20
dtype: int64

In [23]:
# drop null values
data.dropna(inplace=True)

In [24]:
# check colunmn info
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317 entries, 0 to 333
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          317 non-null    object
 1   Age                 317 non-null    float64
 2   Gender              317 non-null    object
 3   Protein1            317 non-null    float64
 4   Protein2            317 non-null    float64
 5   Protein3            317 non-null    float64
 6   Protein4            317 non-null    float64
 7   Tumour_Stage        317 non-null    object
 8   Histology           317 non-null    object
 9   ER status           317 non-null    object
 10  PR status           317 non-null    object
 11  HER2 status         317 non-null    object
 12  Surgery_type        317 non-null    object
 13  Date_of_Surgery     317 non-null    object
 14  Date_of_Last_Visit  317 non-null    object
 15  Patient_Status      317 non-null    object
dtypes: float64(5), object(11)
memory usage: 42.1+ KB

In [25]:
# check gender column info
print(data.Gender.value_counts())

Gender
FEMALE    313
MALE        4
Name: count, dtype: int64

In [26]:
# Tumour Stage
stage = data["Tumour_Stage"].value_counts()
transactions = stage.index
quantity = stage.values

figure = px.pie(data,
             values=quantity,
             names=transactions,hole = 0.5,
             title="Tumour Stages of Patients")
figure.show()

In [27]:
stage

Tumour_Stage
II     180
III     77
I       60
Name: count, dtype: int64

In [28]:
# Histology
histology = data["Histology"].value_counts()
transactions = histology.index
quantity = histology.values
figure = px.pie(data,
             values=quantity,
             names=transactions,hole = 0.5,
             title="Histology of Patients")
figure.show()

In [29]:
histology

Histology
Infiltrating Ductal Carcinoma     224
Infiltrating Lobular Carcinoma     81
Mucinous Carcinoma                 12
Name: count, dtype: int64

In [30]:
# ER status
print(data["ER status"].value_counts())
# PR status
print(data["PR status"].value_counts())
# HER2 status
print(data["HER2 status"].value_counts())

ER status
Positive    317
Name: count, dtype: int64
PR status
Positive    317
Name: count, dtype: int64
HER2 status
Negative    288
Positive     29
Name: count, dtype: int64

In [31]:
# Surgery_type
surgery = data["Surgery_type"].value_counts()
transactions = surgery.index
quantity = surgery.values
figure = px.pie(data,
             values=quantity,
             names=transactions,hole = 0.5,
             title="Type of Surgery of Patients")
figure.show()

In [32]:
# Transform categorical values to numerical values
data["Tumour_Stage"] = data["Tumour_Stage"].map({"I": 1, "II": 2, "III": 3})
data["Histology"] = data["Histology"].map({"Infiltrating Ductal Carcinoma": 1,
                                           "Infiltrating Lobular Carcinoma": 2, "Mucinous Carcinoma": 3})
data["ER status"] = data["ER status"].map({"Positive": 1})
data["PR status"] = data["PR status"].map({"Positive": 1})
data["HER2 status"] = data["HER2 status"].map({"Positive": 1, "Negative": 2})
data["Gender"] = data["Gender"].map({"MALE": 0, "FEMALE": 1})
data["Surgery_type"] = data["Surgery_type"].map({"Other": 1, "Modified Radical Mastectomy": 2,
                                                 "Lumpectomy": 3, "Simple Mastectomy": 4})
print(data.head())

     Patient_ID   Age  Gender  Protein1  Protein2  Protein3  Protein4  \
0  TCGA-D8-A1XD  36.0       1  0.080353   0.42638   0.54715  0.273680
1  TCGA-EW-A1OX  43.0       1 -0.420320   0.57807   0.61447 -0.031505
2  TCGA-A8-A079  69.0       1  0.213980   1.31140  -0.32747 -0.234260
3  TCGA-D8-A1XR  56.0       1  0.345090  -0.21147  -0.19304  0.124270
4  TCGA-BH-A0BF  56.0       1  0.221550   1.90680   0.52045 -0.311990

   Tumour_Stage  Histology  ER status  PR status  HER2 status  Surgery_type  \
0             3          1          1          1            2             2
1             2          3          1          1            2             3
2             3          1          1          1            2             1
3             2          1          1          1            2             2
4             2          1          1          1            2             1

  Date_of_Surgery Date_of_Last_Visit Patient_Status
0       15-Jan-17          19-Jun-17          Alive
1       26-Apr-17          09-Nov-18           Dead
2       08-Sep-17          09-Jun-18          Alive
3       25-Jan-17          12-Jul-17          Alive
4       06-May-17          27-Jun-19           Dead

In [33]:
# Splitting data
x = np.array(data[['Age', 'Gender', 'Protein1', 'Protein2', 'Protein3','Protein4',
                   'Tumour_Stage', 'Histology', 'ER status', 'PR status',
                   'HER2 status', 'Surgery_type']])
y = np.array(data['Patient_Status'])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=42)

In [34]:
model = SVC()

In [35]:
model

SVC()

In [36]:
model.fit(x_train, y_train)

SVC()

In [38]:
model.score(x_test, y_test)

0.8125

In [37]:
# Prediction
# features = [['Age', 'Gender', 'Protein1', 'Protein2', 'Protein3','Protein4', 'Tumour_Stage', 'Histology', 'ER status', 'PR status', 'HER2 status', 'Surgery_type']]
features = np.array([[36.0, 1, 0.080353, 0.42638, 0.54715, 0.273680, 3, 1, 1, 1, 2, 2,]])
print(model.predict(features))

['Alive']