In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [37]:
path = 'https://raw.githubusercontent.com/amankharwal/Website-data/master/TravelInsurancePrediction.csv'

In [38]:
df = pd.read_csv(path)
df.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad,TravelInsurance
0,0,31,Government Sector,Yes,400000,6,1,No,No,0
1,1,31,Private Sector/Self Employed,Yes,1250000,7,0,No,No,0
2,2,34,Private Sector/Self Employed,Yes,500000,4,1,No,No,1
3,3,28,Private Sector/Self Employed,Yes,700000,3,1,No,No,0
4,4,28,Private Sector/Self Employed,Yes,700000,8,1,Yes,No,0

In [39]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [40]:
df.isnull().sum()

Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  1987 non-null   int64
 1   Employment Type      1987 non-null   object
 2   GraduateOrNot        1987 non-null   object
 3   AnnualIncome         1987 non-null   int64
 4   FamilyMembers        1987 non-null   int64
 5   ChronicDiseases      1987 non-null   int64
 6   FrequentFlyer        1987 non-null   object
 7   EverTravelledAbroad  1987 non-null   object
 8   TravelInsurance      1987 non-null   int64
dtypes: int64(5), object(4)
memory usage: 139.8+ KB

In [42]:
df["TravelInsurance"] = df["TravelInsurance"].map({0: "Not Purchased", 1: "Purchased"})

In [43]:
# explore the age column to see how age affects the purchase of an insurance policy:

import plotly.express as px
df = df
figure = px.histogram(df, x = "Age",
                      color = "TravelInsurance",
                      title= "Factors Affecting Purchase of Travel Insurance: Age")
figure.show()

In [44]:
# explore how a person’s type of employment affects the purchase of an insurance policy:

figure = px.histogram(df, x = "Employment Type",
                      color = "TravelInsurance",
                      title= "Factors Affecting Purchase of Travel Insurance: Employment Type")
figure.show()

In [45]:
df["GraduateOrNot"] = df["GraduateOrNot"].map({"No": 0, "Yes": 1})
df["FrequentFlyer"] = df["FrequentFlyer"].map({"No": 0, "Yes": 1})
df["EverTravelledAbroad"] = df["EverTravelledAbroad"].map({"No": 0, "Yes": 1})
df.head()

,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad,TravelInsurance
0,31,Government Sector,1,400000,6,1,0,0,Not Purchased
1,31,Private Sector/Self Employed,1,1250000,7,0,0,0,Not Purchased
2,34,Private Sector/Self Employed,1,500000,4,1,0,0,Purchased
3,28,Private Sector/Self Employed,1,700000,3,1,0,0,Not Purchased
4,28,Private Sector/Self Employed,1,700000,8,1,1,0,Not Purchased

In [46]:
x = np.array(df[["Age", "GraduateOrNot",
                   "AnnualIncome", "FamilyMembers",
                   "ChronicDiseases", "FrequentFlyer",
                   "EverTravelledAbroad"]])
y = np.array(df[["TravelInsurance"]])

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=72)

In [48]:
model = DecisionTreeClassifier()

In [49]:
model

DecisionTreeClassifier()

In [50]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
predictions = model.predict(x_test)

In [53]:
model.score(x_test, y_test)

0.7989949748743719